defaults:
- config_schema

seed: 1
seq_len: 1024
examples: 512
max_text_token_id: 2048
image_size: 128
patch_size: 16
images_per_example: 3
flat_tokens_config:
  tokens_chunk_size: 4194304
  seq_starts_chunk_size: 65536
  image_chunk_size: 65536